In [ ]:
# Outlier removal using z-score : 
# If we want to remove outliers using z-score method then our column must be normally distributed.
# Z-score is calculated as (X - mean) / std deviation
# If the z-score is greater than 3 or less than -3 then we can consider it as an outlier.


# Now how to treat outliers.

# There are 2 popular methods to treat outliers :

# 1. Trimming :
# -> In this method we simply remove the outliers from our dataset. This method is simple and effective but it can lead to loss of data if we have a lot of outliers.

# 2. Capping:
# -> In this method we replace the outliers with a certain value. This value can be the maximum or minimum value of the column or it can be a value that is calculated using some method like IQR (Interquartile Range) method. This method is useful when we have a lot of outliers and we don't want to lose data.

In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('placement.csv')
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [6]:
df.shape

(1000, 3)

In [10]:
plt.figure(figsize=(16,5))
plt.subplot(1,2,1)
sns.histplot(df['cgpa'],kde=True)

plt.subplot(1,2,2)
sns.histplot(df['placement_exam_marks'],kde=True)

plt.show()

In [11]:
df['placement_exam_marks'].skew()

np.float64(0.8356419499466834)

In [12]:
print("Mean value of cgpa : ",df['cgpa'].mean())
print("Standard deviation of cgpa : ",df['cgpa'].std())
print("Min value of cgpa : ",df['cgpa'].min())
print("Max value of cgpa : ",df['cgpa'].max())

Mean value of cgpa :  6.96124
Standard deviation of cgpa :  0.6158978751323896
Min value of cgpa :  4.89
Max value of cgpa :  9.12

In [13]:
print("Highest value allowed",df['cgpa'].mean() + 3 * df['cgpa'].std())
print("Lowest value allowed",df['cgpa'].mean() - 3 * df['cgpa'].std())

Highest value allowed 8.808933625397168
Lowest value allowed 5.113546374602832

In [16]:
# finding outliers 

df[(df['cgpa'] > 8.80) | (df['cgpa'] < 5.11)]

     cgpa  placement_exam_marks  placed
485  4.92                  44.0       1
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
999  4.90                  10.0       1

In [17]:
new_df = df[(df['cgpa'] <= 8.80) & (df['cgpa'] >= 5.11)]
new_df.shape

(995, 3)

In [20]:
## approach 2 : using z score

df['z_score_CGPA'] = ((df['cgpa']- df['cgpa'].mean()) / df['cgpa'].std())

In [21]:
df['z_score_CGPA']

0      0.371425
1      0.809810
2      0.939701
3     -0.878782
4      0.436371
         ...
995    3.099150
996    3.505062
997   -3.362960
998    2.693239
999   -3.346724
Name: z_score_CGPA, Length: 1000, dtype: float64

In [22]:
df[df['z_score_CGPA'] > 3]

     cgpa  placement_exam_marks  placed  z_score_CGPA
995  8.87                  44.0       1      3.099150
996  9.12                  65.0       1      3.505062

In [23]:
df[df['z_score_CGPA'] < -3]

     cgpa  placement_exam_marks  placed  z_score_CGPA
485  4.92                  44.0       1     -3.314251
997  4.89                  34.0       0     -3.362960
999  4.90                  10.0       1     -3.346724

In [30]:
df[(df['z_score_CGPA'] > 3 ) | (df['z_score_CGPA'] < -3)]

     cgpa  placement_exam_marks  placed  z_score_CGPA
485  4.92                  44.0       1     -3.314251
995  8.87                  44.0       1      3.099150
996  9.12                  65.0       1      3.505062
997  4.89                  34.0       0     -3.362960
999  4.90                  10.0       1     -3.346724

In [31]:
new_df = df[(df['z_score_CGPA'] < 3 ) & (df['z_score_CGPA'] > -3)]

In [32]:
new_df.shape

(995, 4)

#  Capping

In [33]:
upper_limit = df['cgpa'].mean() + 3 * df['cgpa'].std()
lower_limit = df['cgpa'].mean() - 3 * df['cgpa'].std()

In [34]:
df['cgpa'] = np.where(
    df['cgpa'] > upper_limit,upper_limit,
    np.where(
        df['cgpa'] < lower_limit,lower_limit,df['cgpa']
    )

)

In [35]:
df.head()

   cgpa  placement_exam_marks  placed  z_score_CGPA
0  7.19                  26.0       1      0.371425
1  7.46                  38.0       1      0.809810
2  7.54                  40.0       1      0.939701
3  6.42                   8.0       1     -0.878782
4  7.23                  17.0       0      0.436371

In [36]:
df.shape

(1000, 4)

In [37]:
df.describe()

              cgpa  placement_exam_marks       placed  z_score_CGPA
count  1000.000000           1000.000000  1000.000000  1.000000e+03
mean      6.961499             32.225000     0.489000 -1.465494e-16
std       0.612688             19.130822     0.500129  1.000000e+00
min       5.113546              0.000000     0.000000 -3.362960e+00
25%       6.550000             17.000000     0.000000 -6.677081e-01
50%       6.960000             28.000000     0.000000 -2.013321e-03
75%       7.370000             44.000000     1.000000  6.636815e-01
max       8.808934            100.000000     1.000000  3.505062e+00