In [1]:
import numpy as np 
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [8]:
date['date_year'] = date['date'].dt.year

In [9]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [10]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [11]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

In [12]:
date = date.drop(columns=['day_pf_week'])

KeyError: "['day_pf_week'] not found in axis"

In [13]:
date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

In [14]:
# day of week - name

date['day_of_week_name'] =  date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week_name
0,2019-12-10,5628,25,3,2019,12,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,Saturday
4,2019-01-06,4344,25,3,2019,1,6,Sunday

In [15]:
# is weekend?
date['is_weekend'] = np.where(date['day_of_week_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,Sunday,1

In [16]:
#Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week


date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week_name,is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,17,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,6,Sunday,1,1

In [17]:
#Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,day_of_week_name,is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,Tuesday,0,50,4
1,2018-08-15,2018,8,15,Wednesday,0,33,3
2,2018-10-23,2018,10,23,Tuesday,0,43,4
3,2019-08-17,2019,8,17,Saturday,1,33,3
4,2019-01-06,2019,1,6,Sunday,1,1,1

In [36]:
# Extract Time elapsed between dates

In [18]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 28, 13, 47, 3, 467252)

In [19]:
today - date['date']

0     2300 days 13:47:03.467252
1     2782 days 13:47:03.467252
2     2713 days 13:47:03.467252
3     2415 days 13:47:03.467252
4     2638 days 13:47:03.467252
                 ...
995   2728 days 13:47:03.467252
996   2669 days 13:47:03.467252
997   2517 days 13:47:03.467252
998   2582 days 13:47:03.467252
999   2356 days 13:47:03.467252
Name: date, Length: 1000, dtype: timedelta64[ns]

In [20]:
(today - date['date']).dt.days

0      2300
1      2782
2      2713
3      2415
4      2638
       ...
995    2728
996    2669
997    2517
998    2582
999    2356
Name: date, Length: 1000, dtype: int64

In [21]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week_name,is_weekend,date_week,quarter,months_passed
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,0,50,4,75
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,0,33,3,91
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,0,43,4,89
3,2019-08-17,7292,25,1,2019,8,17,Saturday,1,33,3,79
4,2019-01-06,4344,25,3,2019,1,6,Sunday,1,1,1,86

In [22]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [23]:
time['date'] = pd.to_datetime(time['date'])
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [25]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [26]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [58]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00