In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [ ]:
date.head()

In [ ]:
time.head()

In [ ]:
date.info()

In [ ]:
date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

In [ ]:
date['date_year'] = date['date'].dt.year

In [ ]:
date.head()

In [ ]:
date['date_month'] = date['date'].dt.month
date.head()

In [ ]:
date['date_day'] = date['date'].dt.day
date.head()

In [23]:
date = date.drop(columns=['day_pf_week'])

In [24]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [27]:
# day of week - name

date['day_of_week_name'] =  date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week,day_of_week_name
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday

In [30]:
# is weekend?
date['is_weekend'] = np.where(date['day_of_week_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week,day_of_week_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday,1

In [34]:
#Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week


date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week,day_of_week_name,is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday,1,1

In [35]:
#Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,day_of_week,day_of_week_name,is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

In [36]:
# Extract Time elapsed between dates

In [37]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 2, 16, 16, 3, 3, 204480)

In [38]:
today - date['date']

0     2260 days 16:03:03.204480
1     2742 days 16:03:03.204480
2     2673 days 16:03:03.204480
3     2375 days 16:03:03.204480
4     2598 days 16:03:03.204480
                 ...
995   2688 days 16:03:03.204480
996   2629 days 16:03:03.204480
997   2477 days 16:03:03.204480
998   2542 days 16:03:03.204480
999   2316 days 16:03:03.204480
Name: date, Length: 1000, dtype: timedelta64[ns]

In [45]:
(today - date['date']).dt.days

0      2260
1      2742
2      2673
3      2375
4      2598
       ...
995    2688
996    2629
997    2477
998    2542
999    2316
Name: date, Length: 1000, dtype: int64

In [48]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,day_of_week,day_of_week_name,is_weekend,date_week,quarter,months_passed
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday,0,50,4,74
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday,0,33,3,90
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday,0,43,4,88
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday,1,33,3,78
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday,1,1,1,85

In [49]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [53]:
time['date'] = pd.to_datetime(time['date'])
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [55]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [57]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [58]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00